parameters:
#    sensukho_lista.example.class: Sensukho\ListaBundle\Example

services:
#    sensukho_lista.example:
#        class: %sensukho_lista.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
